// <auto-generated />
using System;
using Database.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230124161944_Seed_Completed")]
    partial class Seed_Completed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database.Database.Model.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WizzAir"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RyanAir"
                        },
                        new
                        {
                            Id = 3,
                            Name = "British Airways"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Air Serbia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SCAT Airlines"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Belavia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wingo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Iberia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Air France"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Philippine Airlines"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Luxair"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Air China"
                        },
                        new
                        {
                            Id = 13,
                            Name = "AVIANCA"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Aero4M"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Aeromexico"
                        });
                });

            modelBuilder.Entity("Database.Database.Model.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Budapest",
                            Population = 1800000
                        },
                        new
                        {
                            Id = 2,
                            Name = "London",
                            Population = 8800000
                        },
                        new
                        {
                            Id = 3,
                            Name = "Szarajevó",
                            Population = 3500000
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sao Paulo",
                            Population = 12325232
                        },
                        new
                        {
                            Id = 5,
                            Name = "Minszk",
                            Population = 9400000
                        },
                        new
                        {
                            Id = 6,
                            Name = "Asztana",
                            Population = 16700000
                        },
                        new
                        {
                            Id = 7,
                            Name = "Párizs",
                            Population = 2165423
                        },
                        new
                        {
                            Id = 8,
                            Name = "Belgrád",
                            Population = 1378682
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bogotá",
                            Population = 7743955
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dakar",
                            Population = 1438725
                        },
                        new
                        {
                            Id = 11,
                            Name = "Havanna",
                            Population = 2141652
                        },
                        new
                        {
                            Id = 12,
                            Name = "Libreville",
                            Population = 797003
                        },
                        new
                        {
                            Id = 13,
                            Name = "Luxembourg",
                            Population = 132780
                        },
                        new
                        {
                            Id = 14,
                            Name = "Madrid",
                            Population = 3280782
                        },
                        new
                        {
                            Id = 15,
                            Name = "Manila",
                            Population = 1846513
                        },
                        new
                        {
                            Id = 16,
                            Name = "Mexikóváros",
                            Population = 8851080
                        },
                        new
                        {
                            Id = 17,
                            Name = "Moszkva",
                            Population = 12455682
                        },
                        new
                        {
                            Id = 18,
                            Name = "Peking",
                            Population = 21893095
                        },
                        new
                        {
                            Id = 19,
                            Name = "Pozsony",
                            Population = 475503
                        },
                        new
                        {
                            Id = 20,
                            Name = "Prága",
                            Population = 1275406
                        });
                });

            modelBuilder.Entity("Database.Database.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("Distance")
                        .HasColumnType("int");

                    b.Property<int?>("FlightDuration")
                        .HasColumnType("int");

                    b.Property<int?>("FromId")
                        .HasColumnType("int");

                    b.Property<int?>("KmPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FromId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 1,
                            DestinationId = 2,
                            Distance = 1450,
                            FlightDuration = 145,
                            FromId = 1,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 3,
                            DestinationId = 2,
                            Distance = 1450,
                            FlightDuration = 155,
                            FromId = 1,
                            KmPrice = 7
                        },
                        new
                        {
                            Id = 3,
                            AirlineId = 4,
                            DestinationId = 8,
                            Distance = 318,
                            FlightDuration = 54,
                            FromId = 1,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 4,
                            AirlineId = 4,
                            DestinationId = 3,
                            Distance = 198,
                            FlightDuration = 45,
                            FromId = 8,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 5,
                            AirlineId = 3,
                            DestinationId = 14,
                            Distance = 1252,
                            FlightDuration = 155,
                            FromId = 2,
                            KmPrice = 7
                        },
                        new
                        {
                            Id = 6,
                            AirlineId = 3,
                            DestinationId = 2,
                            Distance = 1252,
                            FlightDuration = 155,
                            FromId = 14,
                            KmPrice = 7
                        },
                        new
                        {
                            Id = 7,
                            AirlineId = 5,
                            DestinationId = 17,
                            Distance = 2304,
                            FlightDuration = 235,
                            FromId = 6,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 8,
                            AirlineId = 5,
                            DestinationId = 6,
                            Distance = 2304,
                            FlightDuration = 235,
                            FromId = 17,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 9,
                            AirlineId = 6,
                            DestinationId = 5,
                            Distance = 2961,
                            FlightDuration = 240,
                            FromId = 6,
                            KmPrice = 8
                        },
                        new
                        {
                            Id = 10,
                            AirlineId = 6,
                            DestinationId = 6,
                            Distance = 2961,
                            FlightDuration = 240,
                            FromId = 5,
                            KmPrice = 8
                        },
                        new
                        {
                            Id = 11,
                            AirlineId = 7,
                            DestinationId = 11,
                            Distance = 2230,
                            FlightDuration = 273,
                            FromId = 9,
                            KmPrice = 4
                        },
                        new
                        {
                            Id = 12,
                            AirlineId = 7,
                            DestinationId = 9,
                            Distance = 2230,
                            FlightDuration = 260,
                            FromId = 11,
                            KmPrice = 4
                        },
                        new
                        {
                            Id = 13,
                            AirlineId = 8,
                            DestinationId = 14,
                            Distance = 3170,
                            FlightDuration = 265,
                            FromId = 10,
                            KmPrice = 8
                        },
                        new
                        {
                            Id = 14,
                            AirlineId = 8,
                            DestinationId = 10,
                            Distance = 3170,
                            FlightDuration = 345,
                            FromId = 14,
                            KmPrice = 8
                        },
                        new
                        {
                            Id = 15,
                            AirlineId = 9,
                            DestinationId = 12,
                            Distance = 5467,
                            FlightDuration = 425,
                            FromId = 7,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 16,
                            AirlineId = 15,
                            DestinationId = 16,
                            Distance = 1780,
                            FlightDuration = 245,
                            FromId = 11,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 17,
                            AirlineId = 2,
                            DestinationId = 1,
                            Distance = 471,
                            FlightDuration = 70,
                            FromId = 20,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 18,
                            AirlineId = 2,
                            DestinationId = 20,
                            Distance = 471,
                            FlightDuration = 75,
                            FromId = 1,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 19,
                            AirlineId = 6,
                            DestinationId = 5,
                            Distance = 689,
                            FlightDuration = 85,
                            FromId = 17,
                            KmPrice = 7
                        },
                        new
                        {
                            Id = 20,
                            AirlineId = 15,
                            DestinationId = 16,
                            Distance = 7472,
                            FlightDuration = 655,
                            FromId = 4,
                            KmPrice = 8
                        },
                        new
                        {
                            Id = 21,
                            AirlineId = 15,
                            DestinationId = 4,
                            Distance = 7472,
                            FlightDuration = 595,
                            FromId = 16,
                            KmPrice = 7
                        },
                        new
                        {
                            Id = 22,
                            AirlineId = 10,
                            DestinationId = 18,
                            Distance = 2890,
                            FlightDuration = 305,
                            FromId = 15,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 23,
                            AirlineId = 1,
                            DestinationId = 2,
                            Distance = 1657,
                            FlightDuration = 180,
                            FromId = 3,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 24,
                            AirlineId = 1,
                            DestinationId = 3,
                            Distance = 1657,
                            FlightDuration = 155,
                            FromId = 2,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 25,
                            AirlineId = 11,
                            DestinationId = 13,
                            Distance = 4446,
                            FlightDuration = 425,
                            FromId = 10,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 26,
                            AirlineId = 9,
                            DestinationId = 7,
                            Distance = 1252,
                            FlightDuration = 145,
                            FromId = 1,
                            KmPrice = 8
                        },
                        new
                        {
                            Id = 27,
                            AirlineId = 9,
                            DestinationId = 1,
                            Distance = 1252,
                            FlightDuration = 135,
                            FromId = 7,
                            KmPrice = 8
                        },
                        new
                        {
                            Id = 28,
                            AirlineId = 1,
                            DestinationId = 6,
                            Distance = 3754,
                            FlightDuration = 305,
                            FromId = 1,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 29,
                            AirlineId = 1,
                            DestinationId = 1,
                            Distance = 3754,
                            FlightDuration = 380,
                            FromId = 6,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 30,
                            AirlineId = 11,
                            DestinationId = 13,
                            Distance = 993,
                            FlightDuration = 130,
                            FromId = 1,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 31,
                            AirlineId = 11,
                            DestinationId = 1,
                            Distance = 993,
                            FlightDuration = 130,
                            FromId = 13,
                            KmPrice = 5
                        },
                        new
                        {
                            Id = 32,
                            AirlineId = 2,
                            DestinationId = 14,
                            Distance = 1982,
                            FlightDuration = 210,
                            FromId = 1,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 33,
                            AirlineId = 2,
                            DestinationId = 1,
                            Distance = 1982,
                            FlightDuration = 210,
                            FromId = 14,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 34,
                            AirlineId = 12,
                            DestinationId = 1,
                            Distance = 7371,
                            FlightDuration = 625,
                            FromId = 18,
                            KmPrice = 9
                        },
                        new
                        {
                            Id = 35,
                            AirlineId = 12,
                            DestinationId = 2,
                            Distance = 8196,
                            FlightDuration = 660,
                            FromId = 18,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 36,
                            AirlineId = 12,
                            DestinationId = 18,
                            Distance = 8196,
                            FlightDuration = 660,
                            FromId = 2,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 37,
                            AirlineId = 12,
                            DestinationId = 5,
                            Distance = 6502,
                            FlightDuration = 555,
                            FromId = 18,
                            KmPrice = 9
                        },
                        new
                        {
                            Id = 38,
                            AirlineId = 12,
                            DestinationId = 7,
                            Distance = 8233,
                            FlightDuration = 670,
                            FromId = 18,
                            KmPrice = 11
                        },
                        new
                        {
                            Id = 39,
                            AirlineId = 12,
                            DestinationId = 18,
                            Distance = 8233,
                            FlightDuration = 670,
                            FromId = 7,
                            KmPrice = 11
                        },
                        new
                        {
                            Id = 40,
                            AirlineId = 12,
                            DestinationId = 14,
                            Distance = 9255,
                            FlightDuration = 705,
                            FromId = 18,
                            KmPrice = 12
                        },
                        new
                        {
                            Id = 41,
                            AirlineId = 13,
                            DestinationId = 9,
                            Distance = 8518,
                            FlightDuration = 675,
                            FromId = 2,
                            KmPrice = 11
                        },
                        new
                        {
                            Id = 42,
                            AirlineId = 13,
                            DestinationId = 2,
                            Distance = 8518,
                            FlightDuration = 625,
                            FromId = 9,
                            KmPrice = 11
                        },
                        new
                        {
                            Id = 43,
                            AirlineId = 9,
                            DestinationId = 7,
                            Distance = 348,
                            FlightDuration = 85,
                            FromId = 2,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 44,
                            AirlineId = 9,
                            DestinationId = 2,
                            Distance = 348,
                            FlightDuration = 85,
                            FromId = 7,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 45,
                            AirlineId = 3,
                            DestinationId = 19,
                            Distance = 1556,
                            FlightDuration = 180,
                            FromId = 2,
                            KmPrice = 9
                        },
                        new
                        {
                            Id = 46,
                            AirlineId = 3,
                            DestinationId = 2,
                            Distance = 1556,
                            FlightDuration = 180,
                            FromId = 19,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 47,
                            AirlineId = 12,
                            DestinationId = 19,
                            Distance = 7845,
                            FlightDuration = 645,
                            FromId = 18,
                            KmPrice = 9
                        },
                        new
                        {
                            Id = 48,
                            AirlineId = 12,
                            DestinationId = 18,
                            Distance = 7845,
                            FlightDuration = 635,
                            FromId = 19,
                            KmPrice = 9
                        },
                        new
                        {
                            Id = 49,
                            AirlineId = 14,
                            DestinationId = 9,
                            Distance = 9713,
                            FlightDuration = 715,
                            FromId = 19,
                            KmPrice = 11
                        },
                        new
                        {
                            Id = 50,
                            AirlineId = 14,
                            DestinationId = 19,
                            Distance = 9713,
                            FlightDuration = 715,
                            FromId = 9,
                            KmPrice = 11
                        },
                        new
                        {
                            Id = 51,
                            AirlineId = 1,
                            DestinationId = 12,
                            Distance = 4910,
                            FlightDuration = 540,
                            FromId = 3,
                            KmPrice = 12
                        },
                        new
                        {
                            Id = 52,
                            AirlineId = 1,
                            DestinationId = 3,
                            Distance = 4910,
                            FlightDuration = 510,
                            FromId = 12,
                            KmPrice = 12
                        },
                        new
                        {
                            Id = 53,
                            AirlineId = 15,
                            DestinationId = 16,
                            Distance = 3169,
                            FlightDuration = 340,
                            FromId = 9,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 54,
                            AirlineId = 15,
                            DestinationId = 9,
                            Distance = 3169,
                            FlightDuration = 360,
                            FromId = 16,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 55,
                            AirlineId = 2,
                            DestinationId = 10,
                            Distance = 4860,
                            FlightDuration = 415,
                            FromId = 20,
                            KmPrice = 15
                        },
                        new
                        {
                            Id = 56,
                            AirlineId = 2,
                            DestinationId = 20,
                            Distance = 4860,
                            FlightDuration = 425,
                            FromId = 10,
                            KmPrice = 15
                        },
                        new
                        {
                            Id = 57,
                            AirlineId = 10,
                            DestinationId = 4,
                            Distance = 4996,
                            FlightDuration = 390,
                            FromId = 15,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 58,
                            AirlineId = 10,
                            DestinationId = 15,
                            Distance = 4996,
                            FlightDuration = 390,
                            FromId = 4,
                            KmPrice = 6
                        },
                        new
                        {
                            Id = 59,
                            AirlineId = 2,
                            DestinationId = 20,
                            Distance = 742,
                            FlightDuration = 200,
                            FromId = 8,
                            KmPrice = 10
                        },
                        new
                        {
                            Id = 60,
                            AirlineId = 2,
                            DestinationId = 8,
                            Distance = 742,
                            FlightDuration = 200,
                            FromId = 20,
                            KmPrice = 10
                        });
                });

            modelBuilder.Entity("Database.Database.Model.Flight", b =>
                {
                    b.HasOne("Database.Database.Model.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId");

                    b.HasOne("Database.Database.Model.City", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("Database.Database.Model.City", "From")
                        .WithMany()
                        .HasForeignKey("FromId");

                    b.Navigation("Airline");

                    b.Navigation("Destination");

                    b.Navigation("From");
                });
#pragma warning restore 612, 618
        }
    }
}
